config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments, :only => [:destroy, :edit, :update]
  resources :pins do
    member do
      put 'like', to: "pins#upvote"
    end
    resources :comments , :only => [:create, :new]
  end

  root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pin
  belongs_to :user
end

app/models/pin.rb
  class Pin < ApplicationRecord
  mount_uploader :photo, PinphotoUploader
  belongs_to :user
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pins
  has_many :comments
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_pin
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.pin = @pin
    @comment.user = current_user
    if @comment.save
      redirect_to @pin, notice: "Successfully created added new comment"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.save
      redirect_to pin_path(@pin)
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

  def set_pin
    @pin = Pin.find(params[:pin_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:description, :pin_id)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @pins = Pin.all.order("created_at DESC")
  end

  def show
    @comment = Comment.new
    @comments = Comment.where(pin_id: @pin)
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Successfully created new Pin"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pin.save
      redirect_to @pin, notice: "Successfully updated Pin"
    else
      render 'new'
    end
  end

  def upvote
    @pin.upvote_by(current_user)
    redirect_to pin_path
  end

  def destroy
    @pin.destroy
    redirect_to root_path
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :photo)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for [@pin, @comment] do |f| %>
  <%= f.input :description, input_html: { class: 'form-control'} %>
  <%= f.submit "Add Comment", class: "btn btn-primary", id: "add-comment" %>
<% end %>

app/views/comments/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-brand">
    <%= link_to "Pin Board", root_path %>
  </div>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
    <button type="button" class="btn btn-default navbar-btn">
      <%= link_to "New Pin", new_pin_path %>
    </button>
    <%= link_to "Account", edit_user_registration_path %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
    <button type="button" class="btn btn-default navbar-btn">
      <%= link_to "Sign Up", new_user_registration_path %>
    </button>
    <button type="button" class="btn btn-default navbar-btn">
      <%= link_to "Sign In", new_user_session_path %>
    </button>
    <% end %>
  </ul>
</nav>

app/views/comments/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
      <h1>Edit Comment</h1>
      <%= image_tag(@pin.photo.to_s, alt: 'Image', width: '100%') if @pin.photo? %>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
    </div>
  </div>
</div>
</div>

app/views/comments/index.html.erb
<h1>you are here</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinterestClone</title>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
      <%= render 'navbar' %>
      <div class="container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin) do |f| %>
  <% flash.each do |key, msg| %>
    <%= content_tag :div, msg, :id => key %>
  <% end %>
  <%= f.input :title, input_html: { class: 'form-control'} %>
  <%= f.input :description, input_html: { class: 'form-control'} %>
  <%= f.file_field :photo, input_html:  { class: 'form-control'}, label: "Photo URL" %>
  <%= f.submit "Add Pin", class: "btn btn-primary" %>
<% end %>

app/views/pins/_navbar.html.erb
  <nav class="navbar navbar-default">
    <div class="navbar-brand">
      <%= link_to "Pin Board", root_path %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <button type="button" class="btn btn-default navbar-btn">
        <%= link_to "New Pin", new_pin_path %>
        </button>
        <button type="button" class="btn btn-default navbar-btn">
        <%= link_to "Account", edit_user_registration_path %>
        </button>
        <button type="button" class="btn btn-default navbar-btn">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </button>
        <% else %>
        <button type="button" class="btn btn-default navbar-btn">
          <%= link_to "Sign Up", new_user_registration_path %>
        </button>
        <button type="button" class="btn btn-default navbar-btn">
        <%= link_to "Sign In", new_user_session_path %>
        </button>
      <% end %>
    </ul>
  </nav>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row"><div class="panel panel-default">
    <div class="panel-heading">
      <h1>Edit Pin</h1>
    </div>
    <div class="panel-body">
      <strong>Current Image</strong>
      <br>
      <%= image_tag(@pin.photo.to_s, alt: 'Image', height: "300") if @pin.photo? %>
      <%= render 'form' %>
    </div>
  </div></div>
</div>

app/views/pins/form.html.erb
<h1>New Pin</h1>

<%= simple_form_for @pin do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>
      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
  <%= f.input :title, input_html { class: 'form-control'} %>
  <%= f.description :description, input_html { class: 'form-control'} %>
  <%= f.button "Add Pin", class: "btn btn-primary" %>
<%= end %>

app/views/pins/index.html.erb
<div id="pins" class="transition-enabled">
  <div class="container">
    <div class="row">
        <% @pins.each do |pin| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="box panel panel-default">
          <%= link_to pin_path(pin) do %>
            <%= image_tag(pin.photo.to_s, alt: 'Image') if pin.photo? %>
            <div class="panel-body">
            <h2><%= pin.title %></h2>
            </div>
          <% end %>
        </div>
      </div>
        <% end %>
    </div>
</div>
</div>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Pin</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div id="pin-show" class="row">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="pin_image">
        <%= image_tag(@pin.photo.to_s, alt: 'Image', width: '100%') if @pin.photo? %>
        </div>
      <div class="panel-body">
        <h1><%= @pin.title %></h1>
        <p><%= @pin.description %></p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <% if user_signed_in? %>
              <p>Submitted by <%= @pin.user.email %></p>
            <% end %>
          </div>
          <div class="col-md-6-">
            <div class="btn-group pull-right">
              <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do %>
            <span class="glyphicon glyphicon-heart">
              <%= @pin.get_upvotes.size %>
            </span>
            <% end %>
            <%= link_to "Edit Pin", edit_pin_path %>
            <%= link_to "Delete Pin", pin_path, method: :delete, data: { confirm: "Are you sure?" } %>
            <%= link_to "Back to Home", root_path %>
            </div>
            <br>
            <br>
            <div class="text-center">
              <button type="button" class="btn btn-primary" id="button-modal">Add a New Comment
               <%#= link_to "Add A New Comment", new_pin_comment_path(@pin) %>
             </button>
             <!--  , id: "modal-btn", class: "btn btn-primary", data-toggle: "modal", data-target: "#exampleModal" %> -->
           </div>


           <!-- Modal -->


<!-- this is a modal -->

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" id="form-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header panel-heading">
        <h3 class="modal-title" id="exampleModalLabel">New Comment</h3>
        <button type="button" class="close" id="modal-close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
     <!--  body of the modal -->

     <div class="col-md-6 col-md-offset-3 ">
      <div class="row">
        <div class="panel panel-default">
          <div class="">
          </div>
          <div class="panel-body">
            <%= render 'comments/form' %>
          </div>
        </div>
      </div>
    </div>
      </div>
    </div>
  </div>
</div>



          <!-- end of modal -->



              <% unless @comments.nil? %>
                <% @comments.each do |comment| %>
                <p> <%= comment.description %> - <em><%= comment.user.email %> </em> </p>
                <div class="btn-group pull-right">
                <%  if current_user == comment.user %>
                  <%= link_to "Edit",  edit_comment_path, class: "btn-sm btn-primary" %>
                  <%= link_to "Delete",  comment_path(comment), class: "btn-sm btn-primary" %>
                  <% end %>
                <% end %>
                </div>
              <% end %>

          </div>
        </div>
      </div>
      </div>
      <br>
    </div>
  </div>
</div>